version: '3'

networks:
  arkbot:
    driver: bridge

services:
  db:
    image: "bitnami/postgresql:latest"
    restart: always
    networks:
     - arkbot
#    ports:
#     - '5432:5432'
#    volumes:
#     - /storage/postgresql-persistance:/bitnami/postgresql
    environment:
      POSTGRESQL_PASSWORD: "arkbot"
      POSTGRESQL_USERNAME: "arkbot"
      POSTGRESQL_DATABASE: "arkbot"
  bot:
    image: docker.pkg.github.com/arkrissym/arkbot/arkbot:latest
    restart: always
    networks:
     - arkbot
    volumes:
     - /path/to/your/config.cfg:/app/config.cfg
     - /path/to/your/token.txt:/app/token.txt
     - /path/to/your/riotKey.txt:/app/riotKey.txt
     - /path/to/your/magicShellSoundFolder:/app/sounds/magicShell
    environment:
      DATABASE_URL: "postgres://arkbot:arkbot@db/arkbot"
      DISCORD_TOKEN: "your-token-here"
      RIOT_KEY: "your-key-here"
    depends_on:
      db
