name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: docker.pkg.github.com/arkrissym/arkbot/arkbot:$(date +%s)
      
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_TAG
    - name : List Docker images
      run: docker images
    - name: Login to the registry
      run: echo "${{ secrets.token }}" | docker login -u "${{ secrets.username }}" --password-stdin docker.pkg.github.com
    - name: Push the Docker image
      run: docker push $IMAGE_TAG
