name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: docker.pkg.github.com/arkrissym/arkbot/arkbot
      
    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      run: |
        export IMAGE_TAG=$(date +%s)
        docker build . --file Dockerfile --tag $IMAGE_NAME:$IMAGE_TAG
        docker images
    - name: Push the docker image
      run: |
        echo "${{ secrets.token }}" | docker login -u "${{ secrets.username }}" --password-stdin docker.pkg.github.com
        docker push $IMAGE_NAME:$IMAGE_TAG
